
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 17 17:03:11 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.mtd;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 11;
  public static final int PAR_A = 7;
  public static final int POS = 9;
  public static final int INICIO = 2;
  public static final int CENTRAR = 4;
  public static final int VERTICAL = 5;
  public static final int FIN = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LATERAL = 6;
  public static final int NEG = 10;
  public static final int PAR_C = 8;
}

