
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 12 18:43:46 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.mtd;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int center = 8;
  public static final int mov_u = 3;
  public static final int begin = 2;
  public static final int mov_r = 5;
  public static final int end = 7;
  public static final int EOF = 0;
  public static final int mov_l = 6;
  public static final int error = 1;
  public static final int mov_d = 4;
}

